/*eslint-env node, es6*/
/*eslint no-unused-vars:1*/
/*eslint no-console:0*/

module.exports = [{
    "id": "announcements",
    "position": 2,
    "hidden": false,
    }, {
    "id": "syllabus",
    "position": 3,
    "hidden": false,
    }, {
    "id": "modules",
    "position": 4,
    "hidden": false,
    }, {
    "id": "grades",
    "position": 5,
    "hidden": false,
    }, {
    "id": "people",
    "position": 6,
    "hidden": false,
    }, {
    "id": "pages",
    "position": 7,
    "hidden": true,
    }, {
    "id": "files",
    "position": 8,
    "hidden": true,
    }, {
    "id": "outcomes",
    "position": 9,
    "hidden": true,
    }, {
    "id": "assignments",
    "position": 10,
    "hidden": true,
    }, {
    "id": "quizzes",
    "position": 11,
    "hidden": true,
    }, {
    "id": "discussions",
    "position": 12,
    "hidden": true,
    }, {
    "id": "conferences",
    "position": 13,
    "hidden": true,
    }, {
    "id": "collaborations",
    "position": 14,
    "hidden": true,
    }, {
    "id": "context_external_tool_7",
    "position": 15,
    "hidden": true,
    }, {
    "id": "context_external_tool_2",
    "position": 16,
    "hidden": true,
    }, {
    "id": "context_external_tool_1",
    "position": 17,
    "hidden": true,
    }, {
    "id": "context_external_tool_9",
    "position": 18,
    "hidden": true,
    }, {
    "id": "context_external_tool_103",
    "position": 19,
    "hidden": true,
    }, {
    "id": "context_external_tool_132",
    "position": 20,
    "hidden": true,
    }];
